Use `typing.TYPE_CHECKING` in _own_version_helper.py
pypa/setuptools-scm pull request #1032
Opened 2024-04-15 23:28 UTC by bswck

Separated typing-only imports from runtime imports as part of my open-source mission to improve typing across Python packages.

2024-04-15 23:30 UTC, bswck commented
If we get this merged, I'll continue to make similar changes to the actual codebase.

2024-04-16 06:02 UTC, RonnyPfannschmidt requested changes
I don't consider this a improvement 

Extra conditions plus breakage of runtime inspection is not a win for me 

As far as I'm concerned this is both more complicated and less useful

2024-04-16 11:22 UTC, bswck commented
> Extra conditions plus breakage of runtime inspection is not a win for me

Is runtime inspection needed?

> As far as I'm concerned this is both more complicated and less useful

I see your point. Advantages of the practice are listed here: https://github.com/snok/flake8-type-checking#flake8-type-checking. If you believe it's unnecessary, I'll go ahead and close this.

2024-04-16 12:09 UTC, RonnyPfannschmidt commented
This one looks fundamentally misguided

2024-04-16 12:10 UTC, closed without merging