Adding `prettier` tool
pypa/setuptools-scm pull request #1060
Opened 2024-07-28 14:01 UTC by jamesbraza

I noticed the docs had extra whitespace. This PR add `prettier` and `end-of-file-fixer` to `pre-commit` for standardized spacing

2024-07-28 18:27 UTC, RonnyPfannschmidt requested changes
im happy to add some fixes, but i am well aware why prettier is no longer under pre-commit and i will not add that tool unless the pre-commit maintainers are convinced it wont mess up everything again

i was at the end of said breakages multiple times myself and consider it scorched earth for now

2024-07-28 20:11 UTC, jamesbraza commented
Fwiw this PR uses https://github.com/rbubley/mirrors-prettier (as opposed to the archived https://github.com/pre-commit/mirrors-prettier). Regardless, I reverted the addition of `prettier` to `.pre-commit-config.yaml`.

Are you okay with the changes `prettier` makes? Also, feel free to just close this PR if you're not interested at all, I am not attached to it.

2024-10-01 17:52 UTC, jamesbraza commented
Alright I just rebased this atop `main` 🤓 . Note there is no `mirrors-prettier` here in this PR, just the changes made by the tool, as if it was a ghost 👻

2024-10-01 18:07 UTC, RonnyPfannschmidt commented on docs/extending.md
> +options:
its broken

2024-10-01 18:19 UTC, jamesbraza commented on docs/extending.md
> +options:
Oh dang, too bad. I made https://github.com/prettier/prettier/issues/16713

I will close this PR as this seems to be a critical bug

2024-10-01 18:19 UTC, closed without merging