Apply assorted repo-review rules
pypa/setuptools-scm pull request #1063
Opened 2024-08-04 10:52 UTC by DimitriPapadopoulos

https://learn.scientific-python.org/development/guides/repo-review/?repo=pypa%2Fsetuptools_scm&branch=main

Apply repo-review rules PP306, PP307, PP308
    
> [PP306](https://learn.scientific-python.org/development/guides/pytest#PP306): Specifies strict config
> `--strict-config` should be in `addopts = [...]`. This forces an error if a config setting is misspelled.
> 
> [PP307](https://learn.scientific-python.org/development/guides/pytest#PP307): Specifies strict markers
> `--strict-markers` should be in `addopts = [...]`. This forces all markers to be specified in config, avoiding misspellings.
> 
> [PP308](https://learn.scientific-python.org/development/guides/pytest#PP308): Specifies useful pytest summary
> An explicit summary flag like `-ra` should be in `addopts = [...]` (print summary of all fails/errors).

Apply repo-review rule PC191

> [PC191](https://learn.scientific-python.org/development/guides/style#PC191): Ruff show fixes if fixes enabled
> If `--fix` is present, `--show-fixes` must be too.

Apply repo-review rule RF003

> [RF003](https://learn.scientific-python.org/development/guides/style#RF003): src directory specified if used
> Must specify `src` directory if it exists.

Apply repo-review rule RF103

> [RF103](https://learn.scientific-python.org/development/guides/style#RF103): pyupgrade must be selected
> Must select the pyupgrade `UP` checks.

2024-08-05 08:45 UTC, RonnyPfannschmidt approved these changes
The tool looks very interesting, I'm going to elevate a bit deeper for some details (for example the insisting on prettier I pre commit even though the pre commit upstream discontinued support)

2024-08-05 18:51 UTC, henryiii commented
Next release of sp-repoo-review will accept a maintained fork https://github.com/scientific-python/cookie/pull/461 - if you know of other markdown linters/formatters that should be here too, we can add those. You can always ignore / skip checks you don't care about, though, that's very much expected.

2024-08-05 21:23 UTC, RonnyPfannschmidt requested changes
Let's add the review pre commit hook and add the necessary ignores

2024-08-05 21:24 UTC, RonnyPfannschmidt commented
With hook 🪝 mean the repo review one

2024-08-05 23:12 UTC, henryiii commented
Example at https://github.com/astropy/astropy/blob/aea0ce95d11a243776629b3fda7b0c43a1dd9ecf/.pre-commit-config.yaml#L69

2024-08-06 09:26 UTC, DimitriPapadopoulos commented
I have added the repo-review pre-commit hook, and disabled these issues for now:

[**pyproject.toml**](https://github.com/DimitriPapadopoulos/setuptools_scm/blob/1f157028c176988b67a3a7b0f0d2260581cb2643/pyproject.toml#L131-L132)
Lines 31 to 32 in 1f15702
```toml
[tool.repo-review]
ignore = ["PP305", "GH103", "GH212", "PC111", "PC160", "PC160", "PC170", "PC180", "PC901", "MY100"]
```

2024-08-06 10:10 UTC, RonnyPfannschmidt approved these changes
Thanks 👍🏻

2024-08-06 10:16 UTC, merged