pipx.run entry-points should be setuptools-scm
pypa/setuptools-scm pull request #1081
Opened 2024-10-25 08:42 UTC by paugier

The package is now called setuptools-scm.

`-` are more common than `_` for command names (at least on Linux).

I guess it make more sense to write `pipx run setuptools-scm`.

Note: currently (before next release), this works

```
pipx run --spec setuptools-scm@https://github.com/pypa/setuptools-scm/archive/refs/heads/main.zip setuptools_scm
```

2024-10-25 08:50 UTC, paugier commented
Note for myself: this works

```
pipx run -v --spec setuptools-scm@git+https://github.com/paugier/setuptools_scm.git@fix-pipx-command-name setuptools-scm
```

2024-10-25 08:59 UTC, RonnyPfannschmidt commented
Based in normalization I suspect we will need the old name

I think pipx needs to support normalization flips before we can drop it

2025-01-14 10:51 UTC, RonnyPfannschmidt requested changes
my understanding is that we need both-until normalization is supported

2025-01-14 10:51 UTC, RonnyPfannschmidt commented on pyproject.toml
> +setuptools-scm = "setuptools_scm._cli:main"
```suggestion
setuptools-scm = "setuptools_scm._cli:main"
setuptools_scm = "setuptools_scm._cli:main"
```

2025-01-14 11:26 UTC, paugier commented on pyproject.toml
> +setuptools-scm = "setuptools_scm._cli:main"
Ah ok thanks. I rebased and amended the commit with this change.

2025-01-14 11:30 UTC, RonnyPfannschmidt approved these changes

2025-01-14 12:07 UTC, merged