Add documentation for 'setup.cfg' configuration
pypa/setuptools-scm pull request #323
Opened 2018-12-12 15:49 UTC by stephenfin

An issue with `[egg_info]` was seen with https://github.com/stephenfin/rst2txt. Take the opportunity to highlight this issue along with general `setup.cfg` support.

2018-12-12 17:58 UTC, RonnyPfannschmidt requested changes
great job, the markup enhancements are neat and the added informations realy drive home a more metadata oriented approach

for it to be fully embracing of the setuptools features we also need to show people the patterns needed for minimal setuptools versions, else they are in for bad surprises on enterprise distro style setups

2018-12-13 12:17 UTC, stephenfin commented
> for it to be fully embracing of the setuptools features we also need to show people the patterns needed for minimal setuptools versions, else they are in for bad surprises on enterprise distro style setups

Good call. Done.

2018-12-13 12:46 UTC, anthrotype commented
if you add setuptools_scm to the build requirements in pyproject.toml, then you could do away with setup_requires and eggs altogether, no?

2018-12-13 12:48 UTC, anthrotype commented
maybe for the time being would be better to recommend to add setuptools_scm to both pyproject.toml and the setup_requires, so that newer pips will use the former (and skip the latter as already resolved by the time setup_requires are evaluated), and older pips that don't know about pyproject.toml can keep using setup_requires (provided they don't fail with some obscure SSL error).

2018-12-13 12:52 UTC, stephenfin commented
> maybe for the time being would be better to recommend to add setuptools_scm to both pyproject.toml and the setup_requires, so that newer pips will use the former (and skip the latter as already resolved by the time setup_requires are evaluated), and older pips that don't know about pyproject.toml can keep using setup_requires (provided they don't fail with some obscure SSL error).

Done

2018-12-13 15:50 UTC, RonnyPfannschmidt approved these changes
great work, i'm going to merge later this evening, please give me a note if you wish to streamline history a bit

2018-12-13 16:16 UTC, stephenfin commented
Yup, happy for you to squash the last three commits. I just kept them separate because I've had people complain about force pushing on GitHub.

2018-12-13 16:19 UTC, RonnyPfannschmidt commented
@stephenfin my personal stance is

* i keep commits separate while the pr is being developed
* i will squash my own commits after the review process is done and i never squash commits of others
* i give contributors the opportunity to squash themselves before i merge

2018-12-13 17:15 UTC, stephenfin commented
Oh, that all makes sense. In this particular case though, I'm away from a computer and won't be near one again until next week. As such, if you're happy to squash them, go for it.

2019-01-07 15:43 UTC, marcelm commented on README.rst
> +    section are not defined, as these will interfere with ``setuptools_scm``.
The extra “not” in this line should probably be removed

2019-01-07 15:45 UTC, marcelm commented
This PR would close #315

2019-01-07 16:09 UTC, RonnyPfannschmidt commented
good reminder, it got lost over the holiday season, i'll put it in my week todo

2019-01-16 18:38 UTC, merged