build/test fixes
pypa/setuptools-scm pull request #634
Opened 2021-09-14 21:04 UTC by RonnyPfannschmidt

- enhance mercurial detection in hg_git tests
- drop devpi testenv
- drop flake8 env for pre-commit
- trim down the toml extra and only make it need modern setuptools
- add test requirements as extra
- run tox selfcheck on all tox python versions
- drop unneeded flake8 excludes
- use build to build the artifacts in the chec_dist env
- drop the dist env, setup.py shouldn't be used for that
- minimal acceptance test for dummy pretend versions

2021-09-14 22:01 UTC, FFY00 requested changes

2021-09-14 22:01 UTC, FFY00 commented on src/setuptools_scm/__init__.py
> +    except Exception:
Shouldn't this be `packaging.version.InvalidVersion`? You can re-export `InvalidVersion` from your version helper module.

2021-09-14 22:01 UTC, FFY00 commented on src/setuptools_scm/__init__.py
> +        version_fields = (0, 0, 0)
Wouldn't it be best to use the version as-is -- `version_fields = (version,)`? Afterall, it is perfectly possible that this is a legacy version, and I don't think we should fallback to `0.0.0` unless there is something actually requiring us to.

2021-09-15 06:53 UTC, RonnyPfannschmidt commented on src/setuptools_scm/__init__.py
> +    except Exception:
instead of re-exporting i put the tuple helper into the fle as well

2021-09-26 18:41 UTC, merged