Normalize the dist-name, as per PEP503, when looking for overrides
pypa/setuptools-scm pull request #848
Opened 2023-05-17 14:40 UTC by pelson

Closes #829.

2023-05-17 15:27 UTC, RonnyPfannschmidt requested changes
Lovely, thanks! 

let's add a note on this breaking change to the changelog and land it

2023-05-19 09:42 UTC, RonnyPfannschmidt approved these changes

2023-05-19 09:42 UTC, merged

2023-05-19 09:42 UTC, RonnyPfannschmidt commented
thanks!

2023-05-19 15:42 UTC, pelson commented
> thanks!

Glad we could ship it!

Thanks for the quick response and positive experience! :+1: