Allow opt-out of find_files behavior. (issue 561)
pypa/setuptools-scm pull request #851
Opened 2023-05-23 23:18 UTC by daveware-nv

~Changes it so find_files is only enabled with config parameter `enable_find_files` is set to true, otherwise will always return empty list.~

Adds config argument `enable_find_files` that when set to `false` allows `find_files` behavior to be disabled.

Addresses https://github.com/pypa/setuptools_scm/issues/561

2023-05-26 06:37 UTC, RonnyPfannschmidt requested changes
for legacy support this has to be opt-in

im researching ways to enable this better by adding a new sdist subcommand instead of obtaining a unrelated possibly miss-configured config object for just the file listing

2023-05-29 04:34 UTC, daveware-nv commented
OK, I've switched the default to true.

2023-07-11 16:36 UTC, ljames8 commented
isn't this PR good to be merged now the requested changes have been made ?

2023-09-12 12:23 UTC, RonnyPfannschmidt commented
cant merge this yet as opting out of the file finders possibly opts into version finding + there is a bug

2023-10-12 21:17 UTC, Lenbok commented
@RonnyPfannschmidt Do you have more information, e.g. what is the bug that is preventing this being merged?

2024-02-26 14:54 UTC, webknjaz commented
@daveware-nv looks like the PR title needs to be fixed to reflect the post-review changes. Could you update it?

2024-03-05 10:23 UTC, RonnyPfannschmidt commented
currently there are many merge conflicts - im unable to merge as is

in the next major release i want to switch from file finders to custom setuptools subcommands as currently file finder opt out requires setuptools_scm "opt-in"

2024-08-08 18:33 UTC, jaraco commented
> cant merge this yet as opting out of the file finders possibly opts into version finding + there is a bug

In https://github.com/pypa/setuptools_scm/pull/364#discussion_r349931908, I advocated for there being a separate boolean to enable (or disable) version inference. Probably that needs to be implemented (first) so people can opt out of versions inference as well. Either that, or the `tool.setuptools_scm` needs to be deprecated and superseded by a new name that could have different defaults (and doesn't use the section header to imply enablement of a feature).

2025-07-27 19:45 UTC, RonnyPfannschmidt commented
closing due to lack of follow up

2025-07-27 19:45 UTC, closed without merging