parse `Version` to dump_version
pypa/setuptools-scm pull request #854
Opened 2023-05-25 08:46 UTC by ZhiyuanChen

fixes #853
fixes #818 
fixes #577

2023-05-26 06:47 UTC, RonnyPfannschmidt commented on src/setuptools_scm/__init__.py
> +            version=parsed_version,
i recommend using the name scm_version or parsed_version as input names so it can be distinguished

2023-05-26 06:49 UTC, RonnyPfannschmidt requested changes
thanks for preparing this 

unfortunately the argument rename is a breaking change that will get downstreams by surprise

as such the old name needs to stay and the new object needs to go in by a different name

there may be need for extra considerations wrt what attributes to put on ScmVersion to help formatting

2023-05-26 06:49 UTC, RonnyPfannschmidt commented on src/setuptools_scm/__init__.py
> +    version: Version,
the argument rename is a breaking change change would silently break downstream users
as such

2023-05-26 08:21 UTC, RonnyPfannschmidt reviewed
this looks much better now, thanks!

for completeness i would recommend to add a unit-test that uses a custom template to dump the node in addition to the normal version and checks for it

with the addition of a changelog note on the feature addition this would be ready to merge then

i presume the pdb calls will go away then

:+1:

2023-05-26 09:24 UTC, RonnyPfannschmidt reviewed
I took note that adding the parameter as is, does a avoidable breaking change

I recommend changing it to a optional keyword only parameter

As for testing,there is need for a own test that uses a custom template that's actually using data from the SCM version

2023-05-26 09:24 UTC, RonnyPfannschmidt commented on testing/test_basic_api.py
> +    dump_version(tmp_path, version, scm_version, "second.py")
Unfortunately this doesn't Test The new feature

2023-05-26 09:34 UTC, RonnyPfannschmidt reviewed
Excellent work, thanks

Please confirm if i should squash or merge

I'll give it a last look over once I return to the computer

2023-05-26 09:34 UTC, RonnyPfannschmidt approved these changes

2023-05-26 09:50 UTC, ZhiyuanChen commented
> Excellent work, thanks
> 
> Please confirm if i should squash or merge
> 
> I'll give it a last look over once I return to the computer

Thanks~ I believe it's better to squash the changes, as most commits are redundant"

2023-05-31 17:05 UTC, merged

2023-05-31 17:06 UTC, RonnyPfannschmidt commented
Thanks for enabling this